### ISSUE TITLE
Add a CONTRIBUTING.md file and more labels

### ISSUE THREAD

**Issue by jmerle** [HackerExperience/GameDesign#4]
Two very basic things:

1. Add a CONTRIBUTING.md file with information on how to contribute (or include the information in the readme).
2. Add more labels so we can better categorize suggestions and filter them when searching for specific ones.

**Comment by umamaistempo** [comment]
> Add more labels so we can better categorize suggestions and filter them when searching for specific ones.

If you could suggest some, i can take a look on this :grin:

**Comment by jmerle** [comment]
Since this is about the game's design, I guess it would be a thing to add labels for all parts of the game's design, so like this:

1. server-related
2. internet-related
3. hacking-related
4. general-suggestions

You might go even deeper (like, instead of internet-related, go both lan-related and backbone-related), but I think this would be enough.

Thing is, by default contributors can't add labels to issues (I guess it is possible to give them the necessary permissions, but can't confirm that), so someone with sufficient permissions would need to label new issues with the right labels.

**Comment by renatomassaro** [comment]
Thanks for the suggestions! A better organization of this repo is on my todo list (followed by the content migration from Phabricator). Also, never worked with Github's CONTRIBUTING.md, so I'll take a look how it works.

**Comment by umamaistempo** [comment]
Assigning @renatomassaro. He'll be working on the Contributing file, i'll assist him.

But this will might take some time as right now we're focused on HEBorn closed test for April 23

**Comment by jmerle** [comment]
This repository seems to be abandoned, closing the issue to prevent it from showing up in my open issues.
